### PR TITLE
🌱 Bump CAPI to v1.7.3

### PR DESCRIPTION
**Pull request by mboersma**
**What this PR does / why we need it**:

Updates CAPI to [v1.7.3](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.3) and all that entails. Also bumps the old version used in the `clusterctl` upgrade test to v1.6.6.

**Which issue(s) this PR fixes**:

N/A

/kind cleanup

### CODE REVIEW

**Review by Jont828 — APPROVED** [review]
/lgtm
/approve

**Comment by mboersma** [comment]
> Not mergeable. Job PR Type has not succeeded.

This is confusing.

**Comment by mboersma** [comment]
Something very broken here with the `prow` PR Type plugin.

**Comment by mboersma** [comment]
/close

I reopened this as #260 to work around whatever problem happened here with `PR Type`.

**Pull request closed without merging**
