### PR TITLE
🌱 Rename 'add-on-components.yaml' to 'addon-components.yaml' in make target

### PR DESCRIPTION
**Pull request by Jont828**
**What this PR does / why we need it**: Change the output file of `make release-manifests` to `addon-components.yaml` so it will be compatible with the [clusterctl PR](https://github.com/kubernetes-sigs/cluster-api/pull/8472) to support CAAPH.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
lgtm

please add a PR description

**Review by CecileRobertMichon — COMMENTED** [review]
lgtm

please add a PR description

**Comment by Jont828** [comment]
@CecileRobertMichon Done, I think we need a /lgtm though.

**Pull request merged**
