### PR TITLE
✨ Add visualizer label patch for HelmChartProxy and HelmReleaseProxy

### PR DESCRIPTION
**Pull request by Jont828**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by Jont828** [comment]
Waiting for #207 since it unblocks the e2e test

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
