### PR TITLE
📖 Add release process documentation

### LINKED ISSUE #198: Need docs for "How to do a product release"
**User Story**

As a maintainer of CAAPH, I would like to have simple, foolproof documentation that leads me through creating a product release.

**Detailed Description**

The targets and tooling for doing a release appear to be here, but no documentation. Trying to figure it out without a guide that contains specific steps and commands is fraught with peril.

**Anything else you would like to add:**

/kind feature
/area documentation

### PR DESCRIPTION
**Pull request by mboersma**
**What this PR does / why we need it**:

Adds documentation to help maintainers do CAAPH product releases.

**Which issue(s) this PR fixes**:

Fixes #198

### CODE REVIEW

**Comment by mboersma** [comment]
@Jont828 is there anything to add or change here?

**Review by Jont828 — APPROVED** [review]
/lgtm
/approve

**Comment by Jont828** [comment]
@mboersma I think we're good, feel free to remove the hold when you're ready to merge.

**Pull request merged**
