### PR TITLE
🌱 Convert pointer types in Helm options to regular fields

### LINKED ISSUE #167: Remove unnecessary pointer types in `HelmOptions` type
**User Story**

There are several instances where we are using pointers for fields like `HelmOptions.Install.CreateNamespace`. This is because when it's set to nil, we want to default it to true. However, we can instead use kubebuilder tags to set that default field and no longer need a pointer. Moreover, removing the pointer type makes it show up by default when printing the CRD, as if HelmOptions is nil, the default value of `CreateNamespace` won't get set until `Install` is not nil.

/kind feature

### PR DESCRIPTION
**Pull request by Jont828**
**What this PR does / why we need it**: Remove pointer types used for defaulting and use kubebuilder tags to set those default instead.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #167

### CODE REVIEW

**Comment by mboersma** [comment]
> The following test failed

Is this actually changing the public API? (I can't tell.) That is, could this break code that is currently using CAAPH?

**Comment by Jont828** [comment]
It changes some fields in the public API by going from pointer -> non-pointer. However, this doesn't break any yaml configurations since there's no difference between pointers or not for users.

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
