### PR TITLE
🌱 Bump CAPI to v1.7.1

### LINKED ISSUE #190: CAPI v1.7.0-beta.0 has been released and is ready for testing
CAPI v1.7.0-beta.0 has been released and is ready for testing.
Looking forward to your feedback before v1.7.0 release!

## For quick reference

- [CAPI v1.7.0-beta.0 release notes](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.0-beta.0)
- [Shortcut to CAPI git issues](https://github.com/kubernetes-sigs/cluster-api/issues)

## Following are the planned dates for the upcoming releases

CAPI v1.7.0 will be released on **Tuesday, 16th April 2024**.

More details of the upcoming schedule can be seen at [CAPI v1.7.0 release timeline](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/releases/release-1.7.md#timeline).

### PR DESCRIPTION
**Pull request by mboersma**
**What this PR does / why we need it**:

Updates CAPI to [v1.7.1](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.1) and all that entails.

~~This PR is for testing and isn't intended to be merged yet. We will refresh it when CAPI v1.7.0 is released.~~

**Which issue(s) this PR fixes**:

Fixes #190
Closes #213

/kind cleanup

### CODE REVIEW

**Comment by mboersma** [comment]
The linter failure should be fixed by #181.

**Comment by mboersma** [comment]
/hold

It looks like e2e tests are still pulling CAPI v1.6.1 components. I'll update this PR (and make a separate one to bump `main` to 1.6.3, which is where CAPI is in `go.mod`.)

**Comment by mboersma** [comment]
/hold

Maybe we should merge #213 first.

**Comment by Jont828** [comment]
@mboersma Think you need to rebase here.

**Comment by mboersma** [comment]
> Think you need to rebase here.

Done!

Seems like CAAPH doesn't automatically get the `needs-rebase` tag applied or removed? I thought this was default `prow` behavior.

**Comment by mboersma** [comment]
@Jont828 this is ready for review.

**Review by Jont828 — COMMENTED** [review]
/lgtm

**Pull request merged**
